---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the required packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items: ntp_pkgs
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes
  with_items: ntp_pkgs
  when: ansible_os_family == 'Debian'

- name: Ensure NTP daemon autostart
  sudo: true
  service: name={{ ntp_svc_name }} enabled=yes

- name: Setup NTP daemon config
  sudo: true
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp
