---
- name: update debian packages
  apt: update_cache=true

- name: install NGinx
  apt: name=nginx state=present

- name: copy nginx.conf to the server
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644
  notify: restart nginx

 - name: Remove Default Site Configuration
   file: path=/etc/nginx/sites-enabled/default state=absent
   notify: restart nginx

 - name: Start Nginx
   service: name=nginx state=started
