---
- name: Install all the packages and stuff required for an EXAMPLE SERVICE
  hosts: example_servers
  user: root
  sudo: no
  roles:
    - common
    - mongodb
    - zeromq
    - service_example
    - nodejs
    - nginx
    - python
    - postgresql
    - memcached
