---
# site.yml

- name: Apply common configuration to all target nodes
  hosts: all
  user: vagrant
  sudo: yes
  gather_facts: true
  roles:
    - common
    - ntp
#    - git
#    - { role: sudo, sudo: yes, tags: "sudo" }
#    - { role: openssh, sudo: yes, tags: "ssh" }

- name: Apply settings to web servers: apache, php5-fpm
  hosts: web
  roles:
    - apache
    - debops.php5 # - { role: debops.php5, tags: "debops" } / # ansible-galaxy install debops.php5
#    - nodejs
#    - nginx

- hosts: centos
  gather_facts: false
