---

debian_cache_valid_time: 14400
pkg_common_list:
  - screen
  - tree
  - curl
  - wget
  - unzip
  - tar
  - nano
  - bash-completion
  - htop
  - iptraf
  - ntop
  - nicstat
  - iftop
pkg_latest:
  - tzdata
  - bash
  - openssl
  - openssh
  - tree
  - curl
  - wget
  - git
  - python-devel
  - libselinux-python
  - vim-enhanced
