# roles/mysql/tasks/main.yml
---
- name: 1. Install MySQL server package
  apt: name=mysql-server state=present
  tags: musthave

- name: 2. Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Install python Mysql package #required for mysql_db tasks
  apt: name=python-mysqldb state=present

- name: 3. Create a new database
  mysql_db: name=demo state=present collation=utf8_general_ci

- name: 4. Create a database user
  mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

- name: 5. Install MySQL extension for PHP
  apt: name=php5-mysql state=present

- name: 6. Set MySQL root password
  shell: mysql-server-5.5 mysql-server/root_password password password | debconf-set-selections
  tags: musthave
  
- name: 7. Restart Apache
  service: name=apache2 state=restarted
