---

- name: Regenerate cache
  apt: update_cache=yes cache_valid_time={{ debian_cache_valid_time }}"

- name: install default packages
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - python-dev
    - htop
    - screen
    - tree
    - curl
    - wget
    - unzip
    - tar
    - nano
    - bash-completion 
    - hdparm
    - htop
    - iptraf
    - iperf3
    - ntop
    - nicstat
    - iftop
  tags: common-packages
