---
- name: Regenerate cache
  apt: update_cache=yes

- name: install default packages
  apt: pkg={{ item }} state=installed
#   action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
  with_items:
    - vim
    - python-dev
    - htop
    - screen
  tags: common-packages
