---

- name: install default packages
  yum: pkg={{ item }} state=installed
  with_items:
    - vim-enhanced
    - python-devel
    - {{ pkg_common_list }}
  register: pkg_result
  failed_when: pkg_result.rc != 0
  changed_when: '"Removed" in pkg_result.stdout'
  tags: common-packages
