---

- name: ensure packages list is at the latest version
  yum: name="{{ item }}" state=latest
  with_items: "{{ pkg_latest }}"
  register: pkg_result
  failed_when: pkg_result.rc != 0
  tags:
    - common
    - packages
