---

- name: ensure packages list is at the latest version
  yum: name="{{ item }}" state=latest
  with_items: "{{ pkg_latest }}"
  register: pkg_result
  failed_when: pkg_result.rc != 0
  tags:
    - common
    - packages

- name: set SELinux policy
  selinux: state=disabled
#  selinux: policy=targeted state=permissive

- name: set right timezone
  copy: src=/usr/share/zoneinfo/Europe/Madrid dest=/etc/localtime

- name: create subdirs under home dir
  file: dest={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "/root/software"
    - "/var/backups"
  register: files_created
	notify: some_handler
