---
# drupal_drush.yml

- hosts: all
  sudo: no
  vars:
    drush_version: 7.34
    console_version: 1.1.5
    
  tasks:
  - name: install php-pear
    yum: name=php-pear state=installed

  - name: add drush channel
    shell: pear channel-discover pear.drush.org || true

  - name: install drush
    shell: pear install -f drush/drush

  - name: install console-table
    shell: pear install -f Console_Table-{{ console_version }}

  - name: php requirements
    yum: name=php-mbstring,php-gd,php-xml state=present

  - name: drupal installation
    shell: drush dl drupal-{{ drush_version }}
