---

# Ansible playbook
#
# @author FranLR (2015).

- hosts: all
  gather_facts: yes

  pre_tasks:
#    - name: Update yum cache
#      apt: update_cache=yes cache_valid_time=3600
#      sudo: yes

  tasks:
    - name: install the 'Development tools' package group
      yum: name="@Development tools" state=present
  
    - name: line infile sysctl.conf
      sysctl: name="kernel.hostname" value="localhost.localdomain" reload=yes state=present

    - name: download OCSInventory Agent tarball
      get_url:
        url="https://launchpad.net/ocsinventory-unix-agent/stable-2.1/2.1/+download/Ocsinventory-Unix-Agent-2.1.tar.gz"
        dest="/tmp/"
        force=no
      register: get_ocsinventoryagent
#
#    - debug:
#        msg="ocsinventory agent was downloaded"
#        when: get_ocsinventoryagent|changed

    - name: adjust timezone
      copy: src=/usr/share/zoneinfo/Europe/Madrid dest=/etc/localtime

    - name: create sample dir with two subdirs
      file: path=/root/sample/{{ item }} state=directory owner=root group=root mode=0774
      with_items:
        - me
        - you
        - ' {{ fqdn }}'

#  roles:
#    - geerlingguy.firewall
#    - geerlingguy.ntp
